# Generated by Django 2.1.5 on 2019-01-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='copywriter',
            field=models.BooleanField(default=False),
        ),
    ]
