# Generated by Django 2.1.3 on 2019-04-15 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190121_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='copywriter',
            new_name='moderator',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
