# Generated by Django 2.1.5 on 2019-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190126_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
